# Motor Parameters
# Motor types: 0 No motor, 1 generic Engine, 2 electric Engine

nMotors: 4

#motor 1
motor1/motorType: 1
motor1/rotationDir: -1.0
motor1/input_chan: 0

#features for generic Engine
motor1/s_prop: 0.017
motor1/k_motor: 157
motor1/k_t_p: 0.000462 
motor1/k_omega: 157
motor1/c_prop: 0.074

#motor 2
motor2/motorType: 1
motor2/rotationDir: 1.0
motor2/input_chan: 1

#features for generic Engine
motor2/s_prop: 0.017
motor2/k_motor: 157
motor2/k_t_p: 0.0000462 
motor2/k_omega: 157
motor2/c_prop: 0.074

#motor 3
motor3/motorType: 1
motor3/rotationDir: -1.0
motor3/input_chan: 2

#features for generic Engine
motor3/s_prop: 0.017
motor3/k_motor: 157
motor3/k_t_p: 0.0000462 
motor3/k_omega: 157
motor3/c_prop: 0.074

#motor 4
motor4/motorType: 1
motor4/rotationDir: 1.0
motor4/input_chan: 3

#features for generic Engine
motor4/s_prop: 0.017
motor4/k_motor: 157
motor4/k_t_p: 0.0000462 
motor4/k_omega: 157
motor4/c_prop: 0.074
